spring:
  application:
    name: leave-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5433/workrh_leaves
    username: workrh
    password: workrh

server:
  port: 8082
