spring:
  application:
    name: leave-service
  config:
    import: optional:configserver:http://localhost:9888
  datasource:
    url: jdbc:postgresql://localhost:6433/workrh_leaves
    username: workrh
    password: workrh

server:
  port: 9082
